#ifndef _RESERVATION_H_
#define _RESERVATION_H_
#define FLOW_STATUS_NACK 2
#define FLOW_STATUS_SPEC 1
#define FLOW_STATUS_NORM 0
#define FLOW_STATUS_WAIT 4
#define FLOW_STATUS_NACK_TRANSITION 5
#define FLOW_STATUS_GRANT_TRANSITION 6

#define RES_TYPE_RES 4
#define RES_TYPE_ACK 3
#define RES_TYPE_NACK 2
#define RES_TYPE_GRANT 1
#define RES_TYPE_SPEC 5
#define RES_TYPE_NORM 0

#define RES_STATUS_NONE 0
#define RES_STATUS_ASSIGNED 1
#define RES_STATUS_REORDER 2

#define FLIT_PRI_RES 1
#define FLIT_PRI_GRANT 3
#define FLIT_PRI_ACK 2
#define FLIT_PRI_NACK 2
#define FLIT_PRI_NORM 1
#define FLIT_PRI_SPEC 0

#define RES_RESERVED_VCS 2


#define INJECTION_BUFFER_SIZE 400
#endif
